[package]
name = "navmesh-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
recastnavigation-sys = {version = "1.0.3", features = ["detour"]}
three-rs = {version = "0.1.0", path = "../three-rs"}